dynup:
  ros__parameters:
    # necessary to provide
    engine_rate: 240
    stabilizer:
      end_pause:
        timeout: 10
      trunk_pid:
        pitch:
          p: 0.0
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: True
        roll:
          p: 0.0
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: True
