# This is an example file for a boot-configuration.sh file
# It is located in the home directory and generated by the
# robot compile script using the --game-mode option.

AUTOSTART=true
ROBOT="wolfgang"
WORKSPACE="/home/bitbots/wolfgang_ws"
START_MOTION=true
START_BEAHVIOUR=false
export ROS_MASTER_URI="http://ros-master:11311"
