#uint8 CLASS_PRODUCTION_INFO   = 0
#uint8 CLASS_BAUDRATE          = 2
#uint8 CLASS_OUTPUT_FREEQUENCY = 3
#uint8 CLASS_OUTPUT_CONTENT    = 4
#uint8 CLASS_STANDARD_PARAM    = 5
#uint8 CLASS_MODE              = 77   #0x4D
#uint8 CLASS_NMEA_OUTPUT       = 78   #0x4E

#uint8 ID_REQUEST              = 0
#uint8 ID_MEMERY               = 1
#uint8 ID_FLASH                = 2

uint8 class
uint8 id
uint8 length
uint8[] msg