bitbots_vision:
  ros__parameters:
    topics:
      image: "zed/zed_node/rgb/image_rect_color"
      balls: "balls_in_image"
      robots: "robots_in_image"
      goalposts: "goal_posts_in_image"
      line_mask: "line_mask_in_image"
      debug_image: "debug_image"

    model:
      path: "/path/to/rfdetr_model_dir"

    rfdetr:
      ball_conf_threshold: 0.98
      robot_conf_threshold: 0.9
      goalpost_conf_threshold: 0.98
      default_conf_threshold: 0.99

    components:
      ball_active: true
      robot_active: true
      goalpost_active: false
      line_active: true
      debug_active: false

    ball:
      rating_threshold: 0.5
      max_count: 1

    line:
      mask_threshold: 0.5
      suppress_margin_px: 10
