bitbots_vision:
  ros__parameters:
    topics:
      image: "camera/image_proc"
      balls: "balls_in_image"
      robots: "robots_in_image"
      goalposts: "goal_posts_in_image"
      line_mask: "line_mask_in_image"
      field_mask: "field_mask"
      debug_image: "debug_image"

    model:
      path: "2022_10_07_flo_torso21_yoeox"

    yoeo:
      conf_threshold: 0.5
      nms_threshold: 0.4

    components:
      ball_active: true
      robot_active: true
      goalpost_active: false
      line_active: true
      field_active: true
      debug_active: false

    ball:
      rating_threshold: 0.5
      max_count: 1
