move_head:
  # Max values for the head position
  max_acceleration_yaw:
    type: double
    default_value: 14.0
    description: "Max acceleration for yaw"
    validation:
      bounds<>: [-1, 20]

  max_acceleration_pitch:
    type: double
    default_value: 14.0
    description: "Max acceleration for pitch"
    validation:
      bounds<>: [-1, 20]

  max_yaw:
    type: double_array
    default_value: [-1.23, 1.23]
    description: "Max values for the head position (in radians)"
    validation:
      fixed_size<>: 2
      element_bounds<>: [-3.14, 3.14]

  max_pitch:
    type: double_array
    default_value: [-1.23, 1.01] 
    description: "Max values for the head position (in radians)"
    validation:
      fixed_size<>: 2

  transition_speed:
    type: double
    default_value: 6.0
    description: "Speed (in rad/s) used to smoothly transition from the current head position into a new search pattern when the head mode changes"
    validation:
      bounds<>: [0.1, 10.0]

  look_at:
    pitch_speed:
      type: double
      default_value: 6.0
      description: "pitch speed for the look at action"
      validation:
        bounds<>: [0.0, 8.0]
    yaw_speed:
      type: double
      default_value: 6.0
      description: "yaw speed for the look at action"
      validation:
        bounds<>: [0.0, 8.0]

  # Search pattern for ball
  search_patterns:
    search_ball_penalty:
      cycle_time:
        type: double
        description: "Duration of one full search pattern cycle in seconds"
        default_value: 5.0
        validation:
          gt<>: [0.0]

      yaw_max:
        type: double_array
        default_value: [-30.0, 30.0]
        description: "Maximum yaw values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      pitch_max:
        type: double_array
        default_value: [-5.0, 35.0]
        description: "Maximum pitch values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      scan_lines:
        type: int
        default_value: 2
        description: "Number of scan horizontal lines for the search pattern"
        validation:
          gt_eq<>: [1]

      reduce_last_scanline:
        type: double
        default_value: 0.2
        description: "Reduces last scanline by that factor so that robot does not collide"
        validation:
          bounds<>: [0.0, 1.0]

    search_field_features:
      cycle_time:
        type: double
        description: "Duration of one full search pattern cycle in seconds"
        default_value: 2.0
        validation:
          gt<>: [0.0]

      yaw_max:
        type: double_array
        default_value: [-70.0, 70.0]
        description: "Maximum yaw values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      pitch_max:
        type: double_array
        default_value: [-5.0, 35.0]
        description: "Maximum pitch values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      scan_lines:
        type: int
        default_value: 2
        description: "Number of scan horizontal lines for the search pattern"
        validation:
          gt_eq<>: [1]

      reduce_last_scanline:
        type: double
        default_value: 0.4
        description: "Reduces last scanline by that factor so that robot does not collide"
        validation:
          bounds<>: [0.0, 1.0]

    search_front:
      cycle_time:
        type: double
        description: "Duration of one full search pattern cycle in seconds"
        default_value: 1.0
        validation:
          gt<>: [0.0]

      yaw_max:
        type: double_array
        default_value: [0.0, 0.0]
        description: "Maximum yaw values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      pitch_max:
        type: double_array
        default_value: [-5.0, 35.0]
        description: "Maximum pitch values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      scan_lines:
        type: int
        default_value: 2
        description: "Number of scan horizontal lines for the search pattern"
        validation:
          gt_eq<>: [1]

      reduce_last_scanline:
        type: double
        default_value: 0.0
        description: "Reduces last scanline by that factor so that robot does not collide"
        validation:
          bounds<>: [0.0, 1.0]

    look_forward:
      cycle_time:
        type: double
        description: "Duration of one full search pattern cycle in seconds"
        default_value: 3.0
        validation:
          gt<>: [0.0]

      yaw_max:
        type: double_array
        default_value: [0.0, 0.0]
        description: "Maximum yaw values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      pitch_max:
        type: double_array
        default_value: [0.0, 0.0]
        description: "Maximum pitch values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      scan_lines:
        type: int
        default_value: 2
        description: "Number of scan horizontal lines for the search pattern"
        validation:
          gt_eq<>: [1]

      reduce_last_scanline:
        type: double
        default_value: 0.0
        description: "Reduces last scanline by that factor so that robot does not collide"
        validation:
          bounds<>: [0.0, 1.0]

