move_head:
  # Max values for the head position
  max_acceleration_pan:
    type: double
    default_value: 14.0
    description: "Max acceleration for pan"
    validation:
      bounds<>: [-1, 20]

  max_acceleration_tilt:
    type: double
    default_value: 14.0
    description: "Max acceleration for tilt"
    validation:
      bounds<>: [-1, 20]

  max_pan:
    type: double_array
    default_value: [-1.57, 1.57]
    description: "Max values for the head position (in radians)"
    validation:
      fixed_size<>: 2
      element_bounds<>: [-3.14, 3.14]

  max_tilt:
    type: double_array
    default_value: [-1.2, 0.2]
    description: "Max values for the head position (in radians)"
    validation:
      fixed_size<>: 2

  look_at:
    tilt_speed:
      type: double
      default_value: 6.0
      description: "Tilt speed for the look at action"
      validation:
        bounds<>: [0.0, 8.0]
    pan_speed:
      type: double
      default_value: 6.0
      description: "Pan speed for the look at action"
      validation:
        bounds<>: [0.0, 8.0]

  # Search pattern for ball
  search_patterns:
    search_ball:
      # search pattern speed
      tilt_speed:
        type: double
        description: "Tilt speed for the search pattern"
        default_value: 3.0

      pan_speed:
        type: double
        description: "Pan speed for the search pattern"
        default_value: 3.0

      # Max values for the search pattern
      pan_max:
        type: double_array
        default_value: [90.0, -90.0]
        description: "Maximum pan values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      tilt_max:
        type: double_array
        default_value: [-10.0, -60.0]
        description: "Maximum tilt values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      # Number of scan lines for the search pattern
      scan_lines:
        type: int
        default_value: 2
        description: "Number of scan lines for the search pattern"
        validation:
          gt_eq<>: [1]

      # Reduces last scanline by that factor so that robot does not collide
      reduce_last_scanline:
        type: double
        default_value: 0.2
        description: "Reduces last scanline by that factor so that robot does not collide"
        validation:
          bounds<>: [0.0, 1.0]

    search_ball_penalty:
      tilt_speed:
        type: double
        description: "Tilt speed for the search pattern"
        default_value: 1.0

      pan_speed:
        type: double
        description: "Pan speed for the search pattern"
        default_value: 2.0

      pan_max:
        type: double_array
        default_value: [-30.0, 30.0]
        description: "Maximum pan values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      tilt_max:
        type: double_array
        default_value: [-7.0, -30.0]
        description: "Maximum tilt values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      scan_lines:
        type: int
        default_value: 2
        description: "Number of scan horizontal lines for the search pattern"
        validation:
          gt_eq<>: [1]

      reduce_last_scanline:
        type: double
        default_value: 0.2
        description: "Reduces last scanline by that factor so that robot does not collide"
        validation:
          bounds<>: [0.0, 1.0]

    search_field_features:
      tilt_speed:
        type: double
        description: "Tilt speed for the search pattern"
        default_value: 3.0

      pan_speed:
        type: double
        description: "Pan speed for the search pattern"
        default_value: 3.0

      pan_max:
        type: double_array
        default_value: [-90.0, 90.0]
        description: "Maximum pan values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      tilt_max:
        type: double_array
        default_value: [-10.0, -60.0]
        description: "Maximum tilt values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      scan_lines:
        type: int
        default_value: 2
        description: "Number of scan horizontal lines for the search pattern"
        validation:
          gt_eq<>: [1]

      reduce_last_scanline:
        type: double
        default_value: 0.2
        description: "Reduces last scanline by that factor so that robot does not collide"
        validation:
          bounds<>: [0.0, 1.0]

    search_front:
      tilt_speed:
        type: double
        description: "Tilt speed for the search pattern"
        default_value: 3.0

      pan_speed:
        type: double
        description: "Pan speed for the search pattern"
        default_value: 3.0

      pan_max:
        type: double_array
        default_value: [ 0.0, 0.0 ]
        description: "Maximum pan values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      tilt_max:
        type: double_array
        default_value: [ -10.0, -70.0 ]
        description: "Maximum tilt values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      scan_lines:
        type: int
        default_value: 2
        description: "Number of scan horizontal lines for the search pattern"
        validation:
          gt_eq<>: [1]

      reduce_last_scanline:
        type: double
        default_value: 0.0
        description: "Reduces last scanline by that factor so that robot does not collide"
        validation:
          bounds<>: [0.0, 1.0]

    look_forward:
      tilt_speed:
        type: double
        description: "Tilt speed for the search pattern"
        default_value: 3.0

      pan_speed:
        type: double
        description: "Pan speed for the search pattern"
        default_value: 3.0

      pan_max:
        type: double_array
        default_value: [ 0.0, 0.0 ]
        description: "Maximum pan values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      tilt_max:
        type: double_array
        default_value: [ -7.0, -7.0 ]
        description: "Maximum tilt values for the search pattern (in degrees)"
        validation:
          fixed_size<>: 2

      scan_lines:
        type: int
        default_value: 2
        description: "Number of scan horizontal lines for the search pattern"
        validation:
          gt_eq<>: [1]

      reduce_last_scanline:
        type: double
        default_value: 0.0
        description: "Reduces last scanline by that factor so that robot does not collide"
        validation:
          bounds<>: [0.0, 1.0]

  position_reached_threshold:
    type: double
    default_value: 5.0
    description: "Threshold (in degrees) when a head position is reached and
    the next position will be triggered"
