# goal definition

# name of the animation
string animation

# if the animation commes from the motion, it should be played directly, interrupting other animations and walking
# it's propably falling or standing up
bool motion

---
#result definition
bool successful

---
#feedback
uint8 percent_done