# goal definition

# name of the animation
string animation

# should the animation be played directly, interrupting other animations and walking
bool force

---
#result definition
bool successful

---
#feedback
uint8 percent_done