############
# Feldraum #
############

# Settings override for the f-031 test field

bitbots_localization:
  ros__parameters:
    field:
      size:
        x: 5.45
        y: 3.88
      padding: 0.7
      initialization:
        single_pose:
          x: -2.0
          y: 0.0
          t: 0.0
          