LeftLeg:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin # kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.00001
  kinematics_solver_timeout: 0.01
  mode: gd_c
RightLeg:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin # kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.00001
  kinematics_solver_timeout: 0.01
  mode: gd_c
Legs:
  kinematics_solver_search_resolution: 0.0001
  kinematics_solver_timeout: 0.005
  mode: gd_c
RightArm:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.00001
  kinematics_solver_timeout: 0.01
  mode: gd_c
LeftArm:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.00001
  kinematics_solver_timeout: 0.01
  mode: gd_c
Arms:
  kinematics_solver_search_resolution: 0.00001
  kinematics_solver_timeout: 0.01
  mode: gd_c
Head:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.001
  mode: gd_c
All:
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  mode: gd_c
