
/ceiling_cam_publisher:
  ros__parameters:

    # The tf frame under which the images were published
    camera_frame_id: ceiling_cam

    # The name of the camera (used to discover the camera). The name can be set in the pylon viewer.
    device_user_id: ceiling_cam

    # The CameraInfo URL (Uniform Resource Locator) where the optional intrinsic
    # camera calibration parameters are stored. This URL string will be parsed
    # from the ROS-CameraInfoManager:
    # http://docs.ros.org/api/camera_info_manager/html/classcamera__info__manager_1_1CameraInfoManager.html#details
    camera_info_url: "package://bitbots_ceiling_cam/config/camera_calibration_ceiling_cam.yaml"

    # No subsampling is used for the ceiling camera
    binning_factor_x: 1
    binning_factor_y: 1

    # The target frame rate
    fps: 20.0

    # The exposure time in microseconds
    exposure: 8000.0

    # The target raw gain of the camera sensor (similar to ISO)
    gain: 150
