//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the bitbots_dummyvision package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __bitbots_dummyvision__DUMMYVISION_PARAMSCONFIG_H__
#define __bitbots_dummyvision__DUMMYVISION_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace bitbots_dummyvision
{
  class dummyvision_paramsConfigStatics;
  
  class dummyvision_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(dummyvision_paramsConfig &config, const dummyvision_paramsConfig &max, const dummyvision_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const dummyvision_paramsConfig &config1, const dummyvision_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, dummyvision_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const dummyvision_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, dummyvision_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const dummyvision_paramsConfig &config) const = 0;
      virtual void getValue(const dummyvision_paramsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T dummyvision_paramsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (dummyvision_paramsConfig::* field);

      virtual void clamp(dummyvision_paramsConfig &config, const dummyvision_paramsConfig &max, const dummyvision_paramsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const dummyvision_paramsConfig &config1, const dummyvision_paramsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, dummyvision_paramsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const dummyvision_paramsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, dummyvision_paramsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const dummyvision_paramsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const dummyvision_paramsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, dummyvision_paramsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, dummyvision_paramsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<dummyvision_paramsConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(dummyvision_paramsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class GREEN_MASK_MIN
{
  public:
    GREEN_MASK_MIN()
    {
      state = true;
      name = "green_mask_min";
    }

    void setParams(dummyvision_paramsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("r_min"==(*_i)->name){r_min = boost::any_cast<int>(val);}
        if("g_min"==(*_i)->name){g_min = boost::any_cast<int>(val);}
        if("b_min"==(*_i)->name){b_min = boost::any_cast<int>(val);}
      }
    }

    int r_min;
int g_min;
int b_min;

    bool state;
    std::string name;

    
}green_mask_min;

class GREEN_MASK_MAX
{
  public:
    GREEN_MASK_MAX()
    {
      state = true;
      name = "green_mask_max";
    }

    void setParams(dummyvision_paramsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("r_max"==(*_i)->name){r_max = boost::any_cast<int>(val);}
        if("g_max"==(*_i)->name){g_max = boost::any_cast<int>(val);}
        if("b_max"==(*_i)->name){b_max = boost::any_cast<int>(val);}
      }
    }

    int r_max;
int g_max;
int b_max;

    bool state;
    std::string name;

    
}green_mask_max;

}groups;



//#line 14 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      int r_min;
//#line 16 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      int g_min;
//#line 18 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      int b_min;
//#line 22 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      int r_max;
//#line 24 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      int g_max;
//#line 26 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      int b_max;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("dummyvision_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const dummyvision_paramsConfig &__max__ = __getMax__();
      const dummyvision_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const dummyvision_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const dummyvision_paramsConfig &__getDefault__();
    static const dummyvision_paramsConfig &__getMax__();
    static const dummyvision_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const dummyvision_paramsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void dummyvision_paramsConfig::ParamDescription<std::string>::clamp(dummyvision_paramsConfig &config, const dummyvision_paramsConfig &max, const dummyvision_paramsConfig &min) const
  {
    return;
  }

  class dummyvision_paramsConfigStatics
  {
    friend class dummyvision_paramsConfig;
    
    dummyvision_paramsConfigStatics()
    {
dummyvision_paramsConfig::GroupDescription<dummyvision_paramsConfig::DEFAULT, dummyvision_paramsConfig> Default("Default", "", 0, 0, true, &dummyvision_paramsConfig::groups);
dummyvision_paramsConfig::GroupDescription<dummyvision_paramsConfig::DEFAULT::GREEN_MASK_MIN, dummyvision_paramsConfig::DEFAULT> green_mask_min("green_mask_min", "", 0, 1, true, &dummyvision_paramsConfig::DEFAULT::green_mask_min);
//#line 14 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __min__.r_min = 0;
//#line 14 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __max__.r_min = 255;
//#line 14 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __default__.r_min = 0;
//#line 14 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      green_mask_min.abstract_parameters.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("r_min", "int", 0, "Minimal red value for green mask", "", &dummyvision_paramsConfig::r_min)));
//#line 14 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __param_descriptions__.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("r_min", "int", 0, "Minimal red value for green mask", "", &dummyvision_paramsConfig::r_min)));
//#line 16 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __min__.g_min = 0;
//#line 16 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __max__.g_min = 255;
//#line 16 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __default__.g_min = 0;
//#line 16 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      green_mask_min.abstract_parameters.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("g_min", "int", 0, "Minimal green value for green mask", "", &dummyvision_paramsConfig::g_min)));
//#line 16 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __param_descriptions__.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("g_min", "int", 0, "Minimal green value for green mask", "", &dummyvision_paramsConfig::g_min)));
//#line 18 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __min__.b_min = 0;
//#line 18 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __max__.b_min = 255;
//#line 18 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __default__.b_min = 0;
//#line 18 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      green_mask_min.abstract_parameters.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("b_min", "int", 0, "Minimal blue value for green mask", "", &dummyvision_paramsConfig::b_min)));
//#line 18 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __param_descriptions__.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("b_min", "int", 0, "Minimal blue value for green mask", "", &dummyvision_paramsConfig::b_min)));
//#line 107 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      green_mask_min.convertParams();
//#line 107 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(dummyvision_paramsConfig::AbstractGroupDescriptionConstPtr(new dummyvision_paramsConfig::GroupDescription<dummyvision_paramsConfig::DEFAULT::GREEN_MASK_MIN, dummyvision_paramsConfig::DEFAULT>(green_mask_min)));
//#line 107 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(dummyvision_paramsConfig::AbstractGroupDescriptionConstPtr(new dummyvision_paramsConfig::GroupDescription<dummyvision_paramsConfig::DEFAULT::GREEN_MASK_MIN, dummyvision_paramsConfig::DEFAULT>(green_mask_min)));
dummyvision_paramsConfig::GroupDescription<dummyvision_paramsConfig::DEFAULT::GREEN_MASK_MAX, dummyvision_paramsConfig::DEFAULT> green_mask_max("green_mask_max", "", 0, 2, true, &dummyvision_paramsConfig::DEFAULT::green_mask_max);
//#line 22 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __min__.r_max = 0;
//#line 22 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __max__.r_max = 255;
//#line 22 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __default__.r_max = 255;
//#line 22 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      green_mask_max.abstract_parameters.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("r_max", "int", 0, "Maximal red value for green mask", "", &dummyvision_paramsConfig::r_max)));
//#line 22 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __param_descriptions__.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("r_max", "int", 0, "Maximal red value for green mask", "", &dummyvision_paramsConfig::r_max)));
//#line 24 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __min__.g_max = 0;
//#line 24 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __max__.g_max = 255;
//#line 24 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __default__.g_max = 255;
//#line 24 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      green_mask_max.abstract_parameters.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("g_max", "int", 0, "Maximal green value for green mask", "", &dummyvision_paramsConfig::g_max)));
//#line 24 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __param_descriptions__.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("g_max", "int", 0, "Maximal green value for green mask", "", &dummyvision_paramsConfig::g_max)));
//#line 26 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __min__.b_max = 0;
//#line 26 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __max__.b_max = 255;
//#line 26 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __default__.b_max = 255;
//#line 26 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      green_mask_max.abstract_parameters.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("b_max", "int", 0, "Maximal blue value for green mask", "", &dummyvision_paramsConfig::b_max)));
//#line 26 "/home/marc/catkin_ws/src/bitbots_vision/bitbots_dummyvision/cfg/dummyvision_params.cfg"
      __param_descriptions__.push_back(dummyvision_paramsConfig::AbstractParamDescriptionConstPtr(new dummyvision_paramsConfig::ParamDescription<int>("b_max", "int", 0, "Maximal blue value for green mask", "", &dummyvision_paramsConfig::b_max)));
//#line 107 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      green_mask_max.convertParams();
//#line 107 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(dummyvision_paramsConfig::AbstractGroupDescriptionConstPtr(new dummyvision_paramsConfig::GroupDescription<dummyvision_paramsConfig::DEFAULT::GREEN_MASK_MAX, dummyvision_paramsConfig::DEFAULT>(green_mask_max)));
//#line 107 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(dummyvision_paramsConfig::AbstractGroupDescriptionConstPtr(new dummyvision_paramsConfig::GroupDescription<dummyvision_paramsConfig::DEFAULT::GREEN_MASK_MAX, dummyvision_paramsConfig::DEFAULT>(green_mask_max)));
//#line 233 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(dummyvision_paramsConfig::AbstractGroupDescriptionConstPtr(new dummyvision_paramsConfig::GroupDescription<dummyvision_paramsConfig::DEFAULT, dummyvision_paramsConfig>(Default)));
//#line 353 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<dummyvision_paramsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<dummyvision_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<dummyvision_paramsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    dummyvision_paramsConfig __max__;
    dummyvision_paramsConfig __min__;
    dummyvision_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const dummyvision_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static dummyvision_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &dummyvision_paramsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const dummyvision_paramsConfig &dummyvision_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const dummyvision_paramsConfig &dummyvision_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const dummyvision_paramsConfig &dummyvision_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<dummyvision_paramsConfig::AbstractParamDescriptionConstPtr> &dummyvision_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<dummyvision_paramsConfig::AbstractGroupDescriptionConstPtr> &dummyvision_paramsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const dummyvision_paramsConfigStatics *dummyvision_paramsConfig::__get_statics__()
  {
    const static dummyvision_paramsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = dummyvision_paramsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __DUMMYVISION_PARAMSRECONFIGURATOR_H__
