ARG BASE_IMAGE=bitbots-common:latest
FROM ${BASE_IMAGE}

ARG user=bitbots
USER $user
WORKDIR /home/$user/bitbots_main

# The target image is intended to be empty of project source code initially.
# We copy pixi manifests and install the environment so ROS 2 and rmw_zenohd are available.
COPY --chown=$user:$user pixi.toml pixi.lock ./
RUN /home/$user/.pixi/bin/pixi install

# Switch back to root
USER root
CMD ["default"]
