support_state_detector:
  k: {
    type: double,
    default_value: 0.97,
    description: "Factor for lowpass filtering the foot pressure",
    validation: {
      bounds<>: [0.0, 1.0]
    }
  }

  summed_pressure_threshold_right: {
    type: int,
    default_value: 2500,
    description: "Threshold for detecting whether the robot really stands on right foot. If they overlap, the robot is considered to stand on both feet.",
    validation: {
      bounds<>: [0, 5000]
    }
  }

  summed_pressure_threshold_left: {
    type: int,
    default_value: 2500,
    description: "Threshold for detecting whether the robot really stands on left foot",
    validation: {
      bounds<>: [0, 5000]
    }
  }

  foot_pressure_topic_left: {
    type: string,
    default_value: "foot_pressure_left/filtered",
    description: "Topic for the left foot pressure sensor"
  }

  foot_pressure_topic_right: {
    type: string,
    default_value: "foot_pressure_right/filtered",
    description: "Topic for the right foot pressure sensor"
  }

  debug: {
    type: bool,
    default_value: true,
    description: "Whether debug information should be published"
  }
