# Lab
"172.20.1.11":
  hostname: "kalliope"
  robot_name: "Kalliope"
"172.20.1.12":
  hostname: "mickey"
  robot_name: "Mickey"
"172.20.1.13":
  hostname: "pink"
  robot_name: "Pink"
"172.20.1.14":
  hostname: "romeo"
  robot_name: "Romeo"
"172.20.1.15":
  hostname: "carrie"
  robot_name: "Carrie"
"172.20.1.16":
  hostname: "peter"
  robot_name: "Peter"

# Field
"10.0.6.1":
  hostname: "kalliope"
  robot_name: "Kalliope"
"10.0.6.2":
  hostname: "mickey"
  robot_name: "Mickey"
"10.0.6.3":
  hostname: "pink"
  robot_name: "Pink"
"10.0.6.4":
  hostname: "romeo"
  robot_name: "Romeo"
"10.0.6.5":
  hostname: "carrie"
  robot_name: "Carrie"
"10.0.6.6":
  hostname: "peter"
  robot_name: "Peter"
