#!/usr/bin/env bash
set -euo pipefail

environment_path=$1
shift

if [[ -f "$environment_path/activate.sh" ]]; then
    # Generated by pixi-pack and includes package activation hooks.
    # shellcheck disable=SC1091
    source "$environment_path/activate.sh"
else
    export CONDA_PREFIX="$environment_path"
    export PATH="$environment_path/bin:$PATH"
fi

export RCUTILS_COLORIZED_OUTPUT=1
export RCUTILS_CONSOLE_OUTPUT_FORMAT='[{severity}] [{name}]: {message} ({function_name}() at {file_name}:{line_number})'
export RMW_IMPLEMENTATION=rmw_zenoh_cpp
export COLCON_LOG_LEVEL=30
export PYTHONWARNINGS='ignore:::setuptools.command.install,ignore:::setuptools.command.easy_install,ignore:::pkg_resources,ignore:easy_install command is deprecated,ignore:setup.py install is deprecated,ignore:pkg_resources:DeprecationWarning'

workspace=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
if [[ -f "$workspace/install/setup.sh" ]]; then
    # shellcheck disable=SC1091
    source "$workspace/install/setup.sh"
fi

exec "$@"
