analyzers:
  ros__parameters:
    pub_rate: 10.0 # Optional
    path: 'Robot' # Optional, prepended to all diagnostic output
    Camera:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Camera
      startswith: [ 'CAMERA']
      timeout: 0.2
      find_and_remove_prefix: ['CAMERA']
    Servos:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Servos
      startswith: ['robot_node: DS']
      timeout: 1.0
      find_and_remove_prefix: ['robot_node: DS']
    System:
      type: diagnostic_aggregator/GenericAnalyzer
      path: System
      startswith: ['SYSTEM']
      timeout: 1.0
      find_and_remove_prefix: ['SYSTEM']

