mjlab_walk_node:
  ros__parameters:
    model: walk_mjlab.onnx

    joints:
      ordered_relevant_joint_names: [
        "r_hip_pitch_joint",
        "r_hip_roll_joint",
        "r_thigh_joint",
        "r_calf_joint",
        "r_ankle_pitch_joint",
        "r_ankle_roll_joint",
        "l_hip_pitch_joint",
        "l_hip_roll_joint",
        "l_thigh_joint",
        "l_calf_joint",
        "l_ankle_pitch_joint",
        "l_ankle_roll_joint",
        #"r_shoulder_roll_joint",
        #"l_shoulder_roll_joint",
        #"r_shoulder_pitch_joint",
        #"l_shoulder_pitch_joint",
        #"r_upper_arm_joint",
        #"l_upper_arm_joint",
        #"r_elbow_joint",
        #"l_elbow_joint",
      ] 
      walkready_state: [
        # right
        0.45, 0.0, 0.0, 0.9, 0.45, 0.0,
        #0.6, 0.0, 0.0, 1.2, 0.6, 0.0,
        # left
        -0.45, 0.0, 0.0, -0.9, -0.45, 0.0,
        #-0.6, 0.0, 0.0, -1.2, -0.6, 0.0,
      ]
      kp: [
        # right
        30.0, 30.0, 30.0, 30.0, 30.0, 30.0,
        # left
        30.0, 30.0, 30.0, 30.0, 30.0, 30.0,
      ]
      kd: [
        # right
        1.1, 1.1, 1.1, 1.1, 1.1, 1.1,
        # left
        1.1, 1.1, 1.1, 1.1, 1.1, 1.1,
      ]
      action_scales: [
        # right
        0.35, 0.35, 0.35, 0.35, 0.35, 0.35,
        # left
        0.35, 0.35, 0.35, 0.35, 0.35, 0.35,
      ]
    phase:
      control_dt: 0.02
      gait_frequency: 1.5
      use_phase: True
      initial_phase: [0.0]
    
    command:
      max_linear_velocity_forward: 1.0
      max_linear_velocity_backward: -0.5
      max_linear_velocity_sideways: 0.5
      max_angular_velocity:  1.0 # pi/4
    
    gravity:
      roll_offset: 0.0
      pitch_offset: 0.0

    providers: ["CPUExecutionProvider"]
