image_width: 2048
image_height: 1536
camera_name: rory
camera_matrix:
  rows: 3
  cols: 3
  data: [1336.20231,    0.     , 1015.82206,
            0.     , 1334.43681,  726.95617,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.285950, 0.081479, -0.000093, -0.000320, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1080.60229,    0.     , 1010.03846,    0.     ,
            0.     , 1193.05933,  715.99058,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
