#! /usr/bin/env python#! /usr/bin/env python

# -*- coding: utf8 -*-

from bitbots_cm730.lowlevel.serial import Serial

from bitbots_cm730.lowlevel.controller.controller import Controller
from bitbots_cm730.lowlevel.controller.controller import get_cm730_register_table

CM730 = get_cm730_register_table()
ID_CM730 = 200

ctrl = Controller(Serial("/dev/ttyUSB0"))
ctrl.write_register(ID_CM730, CM730.dxl_power, 0)
