#!/usr/bin/env python
# -*- coding: utf8 -*-

import rospy
from bitbots_cm730.lowlevel.serial import Serial

from bitbots_cm730.lowlevel.controller.controller import Controller
from bitbots_cm730.lowlevel.controller.controller import get_cm730_register_table
from bitbots_cm730.srv import SwitchMotorPower


""" Calling service from CM730 to turn motor power on or off. But only if not using simulator"""
# todo set motor ram here if turned on, bc it lost it
try:
    rospy.wait_for_service("switch_motor_power", timeout=1)
except rospy.ROSException:
    rospy.logfatal("Can't switch of motorpower, seems like the CM730 is missing.")
    exit()
power_switch = rospy.ServiceProxy("switch_motor_power", SwitchMotorPower)
try:
    response = power_switch(True)  # todo do something with respons
except rospy.ServiceException as exc:
    print("Service did not process request: " + str(exc))
# wait for motors
rospy.sleep(1)