#include <cstdlib>
#include <filesystem>
#include <functional>
#include <memory>
#include <string>

#include <cv_bridge/cv_bridge.hpp>
#include <rclcpp/experimental/executors/events_executor/events_executor.hpp>
#include <rclcpp/rclcpp.hpp>
#include <rclcpp/executors/single_threaded_executor.hpp>
#include <rclcpp/parameter_client.hpp>
#include <sensor_msgs/msg/image.hpp>
#include <soccer_vision_2d_msgs/msg/ball.hpp>
#include <soccer_vision_2d_msgs/msg/ball_array.hpp>
#include <soccer_vision_2d_msgs/msg/goalpost.hpp>
#include <soccer_vision_2d_msgs/msg/goalpost_array.hpp>
#include <soccer_vision_2d_msgs/msg/robot.hpp>
#include <soccer_vision_2d_msgs/msg/robot_array.hpp>
#include <soccer_vision_attribute_msgs/msg/robot.hpp>
#include <std_msgs/msg/header.hpp>
#include <vision_msgs/msg/bounding_box2_d.hpp>
#include <vision_msgs/msg/point2_d.hpp>

#include "bitbots_vision/vision_parameters.hpp"  // generated by generate_parameter_library
#include "bitbots_vision/candidate.hpp"
#include "bitbots_vision/debug_image.hpp"
#include "bitbots_vision/model_config.hpp"
#include "bitbots_vision/yoeo_handler.hpp"

namespace bitbots_vision {

// ---------------------------------------------------------------------------
// Helpers for building ROS messages from Candidates
// ---------------------------------------------------------------------------

static vision_msgs::msg::BoundingBox2D make_bbox(const Candidate & c)
{
  vision_msgs::msg::BoundingBox2D bb;
  bb.center.position.x = static_cast<double>(c.center_x());
  bb.center.position.y = static_cast<double>(c.center_y());
  bb.size_x = static_cast<double>(c.width);
  bb.size_y = static_cast<double>(c.height);
  return bb;
}

static soccer_vision_2d_msgs::msg::Ball make_ball_msg(const Candidate & c)
{
  soccer_vision_2d_msgs::msg::Ball msg;
  msg.bb = make_bbox(c);
  msg.center.x = static_cast<double>(c.center_x());
  msg.center.y = static_cast<double>(c.center_y());
  msg.confidence.confidence = c.rating;
  return msg;
}

static soccer_vision_2d_msgs::msg::Goalpost make_goalpost_msg(const Candidate & c)
{
  soccer_vision_2d_msgs::msg::Goalpost msg;
  msg.bb = make_bbox(c);
  msg.confidence.confidence = c.rating;
  return msg;
}

static soccer_vision_2d_msgs::msg::Robot make_robot_msg(const Candidate & c, uint8_t team)
{
  soccer_vision_2d_msgs::msg::Robot msg;
  msg.bb = make_bbox(c);
  msg.attributes.team = team;
  msg.confidence.confidence = c.rating;
  return msg;
}

// ---------------------------------------------------------------------------
// VisionNode
// ---------------------------------------------------------------------------

class VisionNode : public rclcpp::Node
{
public:
  explicit VisionNode(const rclcpp::NodeOptions & opts = rclcpp::NodeOptions{})
  : Node("bitbots_vision", opts)
  {
    // ---------- Parameters ----------
    param_listener_ = std::make_shared<bitbots_vision::ParamListener>(
      get_node_parameters_interface());
    params_ = param_listener_->get_params();

    // ---------- Team color ----------
    team_color_ = fetch_team_color();

    // ---------- Model ----------
    load_model(resolve_model_path(params_.model.path));

    // ---------- Publishers ----------
    // Ball
    ball_pub_ = create_publisher<soccer_vision_2d_msgs::msg::BallArray>(
      params_.topics.balls, rclcpp::QoS(1));
    // Robots
    robot_pub_ = create_publisher<soccer_vision_2d_msgs::msg::RobotArray>(
      params_.topics.robots, rclcpp::QoS(1));
    // Goalposts
    goalpost_pub_ = create_publisher<soccer_vision_2d_msgs::msg::GoalpostArray>(
      params_.topics.goalposts, rclcpp::QoS(1));
    // Line mask
    line_mask_pub_ = create_publisher<sensor_msgs::msg::Image>(
      params_.topics.line_mask, rclcpp::QoS(1));
    // Field mask
    field_mask_pub_ = create_publisher<sensor_msgs::msg::Image>(
      params_.topics.field_mask, rclcpp::QoS(1));
    // Debug image
    debug_image_pub_ = create_publisher<sensor_msgs::msg::Image>(
      params_.topics.debug_image, rclcpp::QoS(1));

    // ---------- Image subscriber ----------
    image_sub_ = create_subscription<sensor_msgs::msg::Image>(
      params_.topics.image, rclcpp::QoS(1),
      std::bind(&VisionNode::image_callback, this, std::placeholders::_1));

    RCLCPP_INFO(get_logger(), "bitbots_vision ready");
  }

private:
  // ---- Parameters ----
  std::shared_ptr<bitbots_vision::ParamListener> param_listener_;
  bitbots_vision::Params params_;

  // ---- Model ----
  std::unique_ptr<YoeoHandler> handler_;
  ModelConfig model_config_;
  std::string loaded_model_path_;

  // ---- Team color ----
  // 0 = UNKNOWN, 1 = BLUE, 2 = RED  (from soccer_vision_attribute_msgs/Robot constants)
  int team_color_{0};

  // ---- Publishers ----
  rclcpp::Publisher<soccer_vision_2d_msgs::msg::BallArray>::SharedPtr ball_pub_;
  rclcpp::Publisher<soccer_vision_2d_msgs::msg::RobotArray>::SharedPtr robot_pub_;
  rclcpp::Publisher<soccer_vision_2d_msgs::msg::GoalpostArray>::SharedPtr goalpost_pub_;
  rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr line_mask_pub_;
  rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr field_mask_pub_;
  rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr debug_image_pub_;

  // ---- Subscriber ----
  rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image_sub_;

  // ---- Debug image ----
  DebugImage debug_image_;

  // ---------------------------------------------------------------------------
  // Model path resolution
  // ---------------------------------------------------------------------------

  std::string resolve_model_path(const std::string & path)
  {
    if (std::filesystem::exists(path)) {
      return path;
    }
    // Try backward-compatible conda convention:  $CONDA_PREFIX/share/bitbots_model_<name>
    const char * prefix = std::getenv("CONDA_PREFIX");
    if (!prefix) {
      prefix = std::getenv("PIXI_PREFIX");
    }
    if (prefix) {
      const std::string resolved =
        std::string(prefix) + "/share/bitbots_model_" + path;
      if (std::filesystem::exists(resolved)) {
        RCLCPP_INFO(get_logger(), "Resolved model path: %s", resolved.c_str());
        return resolved;
      }
    }
    RCLCPP_WARN(
      get_logger(),
      "Model path '%s' does not exist and could not be resolved via CONDA_PREFIX / PIXI_PREFIX",
      path.c_str());
    return path;
  }

  // ---------------------------------------------------------------------------
  // Model loading
  // ---------------------------------------------------------------------------

  void load_model(const std::string & model_path)
  {
    RCLCPP_INFO(get_logger(), "Loading model from: %s", model_path.c_str());
    model_config_ = ModelConfig::load_from(model_path);

    YoeoHandler::Config cfg;
    cfg.conf_threshold = static_cast<float>(params_.yoeo.conf_threshold);
    cfg.nms_threshold = static_cast<float>(params_.yoeo.nms_threshold);

    handler_ = std::make_unique<YoeoHandler>(model_path, model_config_, cfg, get_logger());
    loaded_model_path_ = model_path;
  }

  // ---------------------------------------------------------------------------
  // Team color (non-fatal – defaults to UNKNOWN if blackboard not available)
  // ---------------------------------------------------------------------------

  int fetch_team_color()
  {
    using namespace std::chrono_literals;
    try {
      auto client =
        std::make_shared<rclcpp::AsyncParametersClient>(this, "parameter_blackboard");
      if (!client->wait_for_service(2s)) {
        RCLCPP_WARN(get_logger(), "parameter_blackboard not available; using TEAM_UNKNOWN");
        return 0;
      }
      // Spin a temporary executor to resolve the async call without blocking the node executor.
      rclcpp::executors::SingleThreadedExecutor tmp_exec;
      tmp_exec.add_node(this->get_node_base_interface());
      auto future = client->get_parameters({"team_color"});
      if (tmp_exec.spin_until_future_complete(future, 2s) ==
          rclcpp::FutureReturnCode::SUCCESS)
      {
        auto values = future.get();
        if (!values.empty()) {
          return values[0].as_int();
        }
      }
    } catch (const std::exception & e) {
      RCLCPP_WARN(get_logger(), "Could not fetch team_color: %s", e.what());
    }
    return 0;  // TEAM_UNKNOWN
  }

  // ---------------------------------------------------------------------------
  // Image callback – main processing pipeline
  // ---------------------------------------------------------------------------

  void image_callback(const sensor_msgs::msg::Image::SharedPtr image_msg)
  {
    // Pick up any parameter changes
    if (param_listener_->is_old(params_)) {
      params_ = param_listener_->get_params();
      reconfigure();
    }

    if (!handler_) {
      return;
    }

    cv::Mat bgr_image;
    try {
      bgr_image = cv_bridge::toCvCopy(image_msg, "bgr8")->image;
    } catch (const cv_bridge::Exception & e) {
      RCLCPP_ERROR(get_logger(), "cv_bridge exception: %s", e.what());
      return;
    }

    const auto & header = image_msg->header;

    debug_image_ = DebugImage(params_.components.debug_active);
    debug_image_.set_image(bgr_image);

    // Run the network once
    handler_->set_image(bgr_image);
    handler_->predict();

    if (params_.components.ball_active) {
      publish_balls(header);
    }
    if (params_.components.robot_active) {
      publish_robots(header);
    }
    if (params_.components.goalpost_active) {
      publish_goalposts(header);
    }
    if (params_.components.line_active) {
      publish_line_mask(header);
    }
    if (params_.components.field_active) {
      publish_field_mask(header);
    }
    if (params_.components.debug_active) {
      publish_debug_image(header);
    }
  }

  // ---------------------------------------------------------------------------
  // Reconfiguration on parameter changes
  // ---------------------------------------------------------------------------

  void reconfigure()
  {
    const std::string new_path = resolve_model_path(params_.model.path);
    if (new_path != loaded_model_path_) {
      load_model(new_path);
      return;  // handler was recreated, thresholds already applied
    }

    if (handler_) {
      YoeoHandler::Config cfg;
      cfg.conf_threshold = static_cast<float>(params_.yoeo.conf_threshold);
      cfg.nms_threshold = static_cast<float>(params_.yoeo.nms_threshold);
      handler_->reconfigure(cfg);
    }
  }

  // ---------------------------------------------------------------------------
  // Per-component publish methods
  // ---------------------------------------------------------------------------

  void publish_balls(const std_msgs::msg::Header & header)
  {
    auto candidates = handler_->get_detection_candidates_for("ball");
    candidates = Candidate::sort_by_rating(candidates);
    if (params_.ball.max_count > 0 &&
        static_cast<int>(candidates.size()) > params_.ball.max_count)
    {
      candidates.resize(static_cast<size_t>(params_.ball.max_count));
    }
    candidates = Candidate::filter_by_rating(
      candidates, static_cast<float>(params_.ball.rating_threshold));

    // Debug – draw all candidates with thin line, selected with thick line
    {
      auto all_cands = handler_->get_detection_candidates_for("ball");
      debug_image_.draw_ball_candidates(all_cands, DebugImage::kBall, 1);
      debug_image_.draw_ball_candidates(candidates, DebugImage::kBall, 3);
    }

    soccer_vision_2d_msgs::msg::BallArray msg;
    msg.header = header;
    for (const auto & c : candidates) {
      msg.balls.push_back(make_ball_msg(c));
    }
    ball_pub_->publish(msg);
  }

  void publish_robots(const std_msgs::msg::Header & header)
  {
    using RobotAttr = soccer_vision_attribute_msgs::msg::Robot;

    soccer_vision_2d_msgs::msg::RobotArray msg;
    msg.header = header;

    if (model_config_.team_colors_provided()) {
      // own_class / opponent_class based on our team color
      const std::string own_class =
        (team_color_ == 1) ? "robot_blue" :
        (team_color_ == 2) ? "robot_red" : "robot_unknown";
      const std::string opp_class =
        (team_color_ == 1) ? "robot_red" :
        (team_color_ == 2) ? "robot_blue" : "robot_unknown";

      for (const auto & c : handler_->get_detection_candidates_for(own_class)) {
        msg.robots.push_back(make_robot_msg(c, RobotAttr::TEAM_OWN));
        debug_image_.draw_box_candidates({c}, DebugImage::kRobotTeamMates, 3);
      }
      for (const auto & c : handler_->get_detection_candidates_for(opp_class)) {
        msg.robots.push_back(make_robot_msg(c, RobotAttr::TEAM_OPPONENT));
        debug_image_.draw_box_candidates({c}, DebugImage::kRobotOpponents, 3);
      }
      // unknown robots (if the model has this class)
      for (const auto & c : handler_->get_detection_candidates_for("robot_unknown")) {
        msg.robots.push_back(make_robot_msg(c, RobotAttr::TEAM_UNKNOWN));
        debug_image_.draw_box_candidates({c}, DebugImage::kRobotUnknown, 3);
      }
    } else {
      for (const auto & c : handler_->get_detection_candidates_for("robot")) {
        msg.robots.push_back(make_robot_msg(c, RobotAttr::TEAM_UNKNOWN));
        debug_image_.draw_box_candidates({c}, DebugImage::kRobotUnknown, 3);
      }
    }

    robot_pub_->publish(msg);
  }

  void publish_goalposts(const std_msgs::msg::Header & header)
  {
    auto candidates = handler_->get_detection_candidates_for("goalpost");

    debug_image_.draw_box_candidates(candidates, DebugImage::kGoalposts, 3);

    soccer_vision_2d_msgs::msg::GoalpostArray msg;
    msg.header = header;
    for (const auto & c : candidates) {
      msg.posts.push_back(make_goalpost_msg(c));
    }
    goalpost_pub_->publish(msg);
  }

  void publish_line_mask(const std_msgs::msg::Header & header)
  {
    cv::Mat mask = handler_->get_segmentation_mask_for("lines");
    if (mask.empty()) {
      return;
    }
    debug_image_.draw_mask(mask, DebugImage::kLines);

    auto img_msg = cv_bridge::CvImage(header, "8UC1", mask).toImageMsg();
    line_mask_pub_->publish(*img_msg);
  }

  void publish_field_mask(const std_msgs::msg::Header & header)
  {
    cv::Mat mask = handler_->get_segmentation_mask_for("field");
    if (mask.empty()) {
      return;
    }

    auto img_msg = cv_bridge::CvImage(header, "8UC1", mask).toImageMsg();
    field_mask_pub_->publish(*img_msg);
  }

  void publish_debug_image(const std_msgs::msg::Header & header)
  {
    auto img_msg =
      cv_bridge::CvImage(header, "bgr8", debug_image_.get_image()).toImageMsg();
    debug_image_pub_->publish(*img_msg);
  }
};

}  // namespace bitbots_vision

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);
  auto node = std::make_shared<bitbots_vision::VisionNode>();
  rclcpp::experimental::executors::EventsExecutor executor;
  executor.add_node(node);
  executor.spin();
  rclcpp::shutdown();
  return 0;
}
