#include <bitbots_vision/candidate.hpp>
#include <bitbots_vision/debug_image.hpp>
#include <bitbots_vision/model_config.hpp>
#include <bitbots_vision/rfdetr_config.hpp>
#include <bitbots_vision/rfdetr_handler.hpp>
#include <bitbots_vision/rfdetr_handler_interface.hpp>
#ifdef BITBOTS_VISION_HAS_TENSORRT
#include <bitbots_vision/tensorrt_handler.hpp>
#endif
#include <bitbots_vision/vision_parameters.hpp>  // generated by generate_parameter_library
#include <cstdlib>
#include <cv_bridge/cv_bridge.hpp>
#include <exception>
#include <filesystem>
#include <functional>
#include <memory>
#include <opencv2/core.hpp>
#include <rclcpp/experimental/executors/events_executor/events_executor.hpp>
#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/image.hpp>
#include <soccer_vision_2d_msgs/msg/ball.hpp>
#include <soccer_vision_2d_msgs/msg/ball_array.hpp>
#include <soccer_vision_2d_msgs/msg/goalpost.hpp>
#include <soccer_vision_2d_msgs/msg/goalpost_array.hpp>
#include <soccer_vision_2d_msgs/msg/robot.hpp>
#include <soccer_vision_2d_msgs/msg/robot_array.hpp>
#include <soccer_vision_attribute_msgs/msg/robot.hpp>
#include <std_msgs/msg/header.hpp>
#include <string>
#include <vision_msgs/msg/bounding_box2_d.hpp>
#include <vision_msgs/msg/point2_d.hpp>

namespace bitbots_vision {

// ---------------------------------------------------------------------------
// Helpers for building ROS messages from Candidates
// ---------------------------------------------------------------------------

static vision_msgs::msg::BoundingBox2D make_bbox(const Candidate& c) {
  vision_msgs::msg::BoundingBox2D bb;
  bb.center.position.x = static_cast<double>(c.center_x());
  bb.center.position.y = static_cast<double>(c.center_y());
  bb.size_x = static_cast<double>(c.width);
  bb.size_y = static_cast<double>(c.height);
  return bb;
}

static soccer_vision_2d_msgs::msg::Ball make_ball_msg(const Candidate& c) {
  soccer_vision_2d_msgs::msg::Ball msg;
  msg.bb = make_bbox(c);
  msg.center.x = static_cast<double>(c.center_x());
  msg.center.y = static_cast<double>(c.center_y());
  msg.confidence.confidence = c.rating;
  return msg;
}

static soccer_vision_2d_msgs::msg::Goalpost make_goalpost_msg(const Candidate& c) {
  soccer_vision_2d_msgs::msg::Goalpost msg;
  msg.bb = make_bbox(c);
  msg.confidence.confidence = c.rating;
  return msg;
}

static soccer_vision_2d_msgs::msg::Robot make_robot_msg(const Candidate& c, uint8_t team) {
  soccer_vision_2d_msgs::msg::Robot msg;
  msg.bb = make_bbox(c);
  msg.attributes.team = team;
  msg.confidence.confidence = c.rating;
  return msg;
}

// ---------------------------------------------------------------------------
// VisionNode
// ---------------------------------------------------------------------------

class VisionNode : public rclcpp::Node {
 public:
  explicit VisionNode(const rclcpp::NodeOptions& opts = rclcpp::NodeOptions{})
      : Node("bitbots_vision", opts),
        param_listener_(std::make_shared<bitbots_vision::ParamListener>(get_node_parameters_interface())) {
    // ---------- Parameters ----------
    params_ = param_listener_->get_params();

    // ---------- Model ----------
    load_model(resolve_model_path(params_.model.path));

    // ---------- Publishers ----------
    // Ball
    ball_pub_ = create_publisher<soccer_vision_2d_msgs::msg::BallArray>(params_.topics.balls, rclcpp::QoS(1));
    // Robots
    robot_pub_ = create_publisher<soccer_vision_2d_msgs::msg::RobotArray>(params_.topics.robots, rclcpp::QoS(1));
    // Goalposts
    goalpost_pub_ =
        create_publisher<soccer_vision_2d_msgs::msg::GoalpostArray>(params_.topics.goalposts, rclcpp::QoS(1));
    // Line mask
    line_mask_pub_ = create_publisher<sensor_msgs::msg::Image>(params_.topics.line_mask, rclcpp::QoS(1));
    // Debug image
    debug_image_pub_ = create_publisher<sensor_msgs::msg::Image>(params_.topics.debug_image, rclcpp::QoS(1));

    // ---------- Image subscriber ----------
    image_sub_ = create_subscription<sensor_msgs::msg::Image>(
        params_.topics.image, rclcpp::QoS(1), std::bind(&VisionNode::image_callback, this, std::placeholders::_1));

    RCLCPP_INFO(get_logger(), "bitbots_vision ready");
  }

 private:
  // ---- Parameters ----
  std::shared_ptr<bitbots_vision::ParamListener> param_listener_;
  bitbots_vision::Params params_;

  // ---- Model ----
  std::unique_ptr<RfdetrHandlerInterface> handler_;
  ModelConfig model_config_;
  std::string loaded_model_path_;

  // ---- Publishers ----
  rclcpp::Publisher<soccer_vision_2d_msgs::msg::BallArray>::SharedPtr ball_pub_;
  rclcpp::Publisher<soccer_vision_2d_msgs::msg::RobotArray>::SharedPtr robot_pub_;
  rclcpp::Publisher<soccer_vision_2d_msgs::msg::GoalpostArray>::SharedPtr goalpost_pub_;
  rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr line_mask_pub_;
  rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr debug_image_pub_;

  // ---- Subscriber ----
  rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image_sub_;

  // ---- Debug image ----
  DebugImage debug_image_;

  // ---------------------------------------------------------------------------
  // Model path resolution
  // ---------------------------------------------------------------------------

  std::string resolve_model_path(const std::string& path) {
    if (std::filesystem::exists(path)) {
      return path;
    }
    // Try backward-compatible conda convention:  $CONDA_PREFIX/share/bitbots_model_<name>
    const char* prefix = std::getenv("CONDA_PREFIX");
    if (!prefix) {
      prefix = std::getenv("PIXI_PREFIX");
    }
    if (prefix) {
      const std::string resolved = std::string(prefix) + "/share/bitbots_model_" + path;
      if (std::filesystem::exists(resolved)) {
        RCLCPP_INFO(get_logger(), "Resolved model path: %s", resolved.c_str());
        return resolved;
      }
    }
    RCLCPP_WARN(get_logger(), "Model path '%s' does not exist and could not be resolved via CONDA_PREFIX / PIXI_PREFIX",
                path.c_str());
    return path;
  }

  // ---------------------------------------------------------------------------
  // Model loading
  // ---------------------------------------------------------------------------

  void load_model(const std::string& model_path) {
    RCLCPP_INFO(get_logger(), "Loading model from: %s", model_path.c_str());

    // Model loading (engine build/parse in particular) has many more
    // failure modes than a plain file-not-found, especially on unfamiliar
    // hardware -- catch broadly here so a bad model/environment disables
    // vision output (handler_ stays null, guarded in image_callback())
    // instead of crashing the whole node.
    try {
      model_config_ = ModelConfig::load_from(model_path);
#ifdef BITBOTS_VISION_HAS_TENSORRT
      RCLCPP_INFO(get_logger(), "TensorRT was available at build time -- using TensorRtHandler");
      handler_ = std::make_unique<TensorRtHandler>(model_path, model_config_, rfdetr_config(), get_logger());
#else
      handler_ = std::make_unique<RfdetrHandler>(model_path, model_config_, rfdetr_config(), get_logger());
#endif
    } catch (const std::exception& e) {
      RCLCPP_ERROR(get_logger(), "Failed to load model from '%s': %s", model_path.c_str(), e.what());
      handler_.reset();
      return;
    }
    loaded_model_path_ = model_path;
  }

  RfdetrConfig rfdetr_config() const {
    RfdetrConfig cfg;
    cfg.class_conf_thresholds = {
        {"ball", static_cast<float>(params_.rfdetr.ball_conf_threshold)},
        {"robot", static_cast<float>(params_.rfdetr.robot_conf_threshold)},
        {"goalpost", static_cast<float>(params_.rfdetr.goalpost_conf_threshold)},
    };
    cfg.default_conf_threshold = static_cast<float>(params_.rfdetr.default_conf_threshold);
    cfg.line_mask_threshold = static_cast<float>(params_.line.mask_threshold);
    return cfg;
  }

  // ---------------------------------------------------------------------------
  // Image callback – main processing pipeline
  // ---------------------------------------------------------------------------

  void image_callback(const sensor_msgs::msg::Image::SharedPtr image_msg) {
    // Pick up any parameter changes
    if (param_listener_->is_old(params_)) {
      params_ = param_listener_->get_params();
      reconfigure();
    }

    if (!handler_) {
      return;
    }

    cv::Mat bgr_image;
    try {
      bgr_image = cv_bridge::toCvCopy(image_msg, "bgr8")->image;
    } catch (const cv_bridge::Exception& e) {
      RCLCPP_ERROR(get_logger(), "cv_bridge exception: %s", e.what());
      return;
    }

    const auto& header = image_msg->header;

    debug_image_ = DebugImage(params_.components.debug_active);
    debug_image_.set_image(bgr_image);

    // Run the network once
    handler_->set_image(bgr_image);
    handler_->predict();

    if (params_.components.ball_active) {
      publish_balls(header);
    }
    if (params_.components.robot_active) {
      publish_robots(header);
    }
    if (params_.components.goalpost_active) {
      publish_goalposts(header);
    }
    if (params_.components.line_active) {
      publish_line_mask(header);
    }
    if (params_.components.debug_active) {
      publish_debug_image(header);
    }
  }

  // ---------------------------------------------------------------------------
  // Reconfiguration on parameter changes
  // ---------------------------------------------------------------------------

  void reconfigure() {
    const std::string new_path = resolve_model_path(params_.model.path);
    if (new_path != loaded_model_path_) {
      load_model(new_path);
      return;  // handler was recreated, thresholds already applied
    }

    if (handler_) {
      handler_->reconfigure(rfdetr_config());
    }
  }

  // ---------------------------------------------------------------------------
  // Per-component publish methods
  // ---------------------------------------------------------------------------

  void publish_balls(const std_msgs::msg::Header& header) {
    auto candidates = handler_->get_detection_candidates_for("ball");
    candidates = Candidate::sort_by_rating(candidates);
    if (params_.ball.max_count > 0 && static_cast<int>(candidates.size()) > params_.ball.max_count) {
      candidates.resize(static_cast<size_t>(params_.ball.max_count));
    }
    candidates = Candidate::filter_by_rating(candidates, static_cast<float>(params_.ball.rating_threshold));

    // Debug – draw all candidates with thin line, selected with thick line
    {
      auto all_cands = handler_->get_detection_candidates_for("ball");
      debug_image_.draw_ball_candidates(all_cands, DebugImage::kBall, 1);
      debug_image_.draw_ball_candidates(candidates, DebugImage::kBall, 3);
    }

    soccer_vision_2d_msgs::msg::BallArray msg;
    msg.header = header;
    for (const auto& c : candidates) {
      msg.balls.push_back(make_ball_msg(c));
    }
    ball_pub_->publish(msg);
  }

  void publish_robots(const std_msgs::msg::Header& header) {
    using RobotAttr = soccer_vision_attribute_msgs::msg::Robot;

    soccer_vision_2d_msgs::msg::RobotArray msg;
    msg.header = header;

    // The RF-DETR model has a single, undifferentiated "robot" class (no
    // team-color information), so all robots publish as TEAM_UNKNOWN.
    for (const auto& c : handler_->get_detection_candidates_for("robot")) {
      msg.robots.push_back(make_robot_msg(c, RobotAttr::TEAM_UNKNOWN));
      debug_image_.draw_box_candidates({c}, DebugImage::kRobotUnknown, 3);
    }

    robot_pub_->publish(msg);
  }

  void publish_goalposts(const std_msgs::msg::Header& header) {
    auto candidates = handler_->get_detection_candidates_for("goalpost");

    debug_image_.draw_box_candidates(candidates, DebugImage::kGoalposts, 3);

    soccer_vision_2d_msgs::msg::GoalpostArray msg;
    msg.header = header;
    for (const auto& c : candidates) {
      msg.posts.push_back(make_goalpost_msg(c));
    }
    goalpost_pub_->publish(msg);
  }

  void publish_line_mask(const std_msgs::msg::Header& header) {
    // Use the raw, unfiltered candidates (before rating-threshold / max-count
    // filtering) so that any real object — even one that won't itself be
    // published — still gets excluded from the line mask.
    std::vector<Candidate> suppress_list;
    for (const char* name : {"ball", "goalpost", "robot"}) {
      auto c = handler_->get_detection_candidates_for(name);
      suppress_list.insert(suppress_list.end(), c.begin(), c.end());
    }

    cv::Mat mask = handler_->get_line_mask();
    if (mask.empty()) {
      return;
    }
    processing::suppress_candidates(mask, suppress_list, params_.line.suppress_margin_px);

    debug_image_.draw_mask(mask, DebugImage::kLines);

    auto img_msg = cv_bridge::CvImage(header, "8UC1", mask).toImageMsg();
    line_mask_pub_->publish(*img_msg);
  }

  void publish_debug_image(const std_msgs::msg::Header& header) {
    auto img_msg = cv_bridge::CvImage(header, "bgr8", debug_image_.get_image()).toImageMsg();
    debug_image_pub_->publish(*img_msg);
  }
};

}  // namespace bitbots_vision

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

int main(int argc, char** argv) {
  // OpenCV's OpenMP thread pool spin-waits between frames and consumes multiple
  // CPU cores even when idle.  For the small network-input images (~384×384)
  // single-threaded OpenCV is faster due to lower synchronisation overhead.
  cv::setNumThreads(1);

  rclcpp::init(argc, argv);
  auto node = std::make_shared<bitbots_vision::VisionNode>();
  rclcpp::experimental::executors::EventsExecutor executor;
  executor.add_node(node);
  executor.spin();
  rclcpp::shutdown();
  return 0;
}
