/**:
  ros__parameters:
    use_sim_time: true
walking:
  ros__parameters:
    engine:

      double_support_ratio: 0.21065044655777365
      foot_distance: 0.18798551840631933
      foot_rise: 0.11811624092819002
      freq: 2.993968323573039
      trunk_height: 0.32637691564562205
      trunk_phase: -0.25332467061367503
      trunk_pitch: 0.41907250744349495
      trunk_pitch_p_coef_forward: -1.3647181211487023
      trunk_pitch_p_coef_turn: -0.006652153811469368
      trunk_swing: 0.42580801916351607
      trunk_x_offset: -0.007025557000380819
      trunk_y_offset: -0.001137005897413421
      trunk_z_movement: 0.02120359533668483
      first_step_swing_factor: 1.0
      first_step_trunk_phase: -0.5
      foot_apex_phase: 0.5
      foot_overshoot_phase: 1.0
      foot_overshoot_ratio: 0.0
      foot_put_down_phase: 1.0
      foot_put_down_z_offset: 0.0
      foot_z_pause: 0.0
      trunk_pause: 0.0
      trunk_x_offset_p_coef_forward: 0.0
      trunk_x_offset_p_coef_turn: 0.0

      kick_length: 0.12
      kick_vel: 0.2
      kick_phase: 0.28
      kick_put_down_phase: 0.8
      kick_rise_factor: 1.5
    node:
      # update frequency of the engine
      engine_freq: 200.0

      # parameters for bioIK
      ik:
        timeout: 0.01
        reset: False

      debug_active: True

      max_step_x: 1.0
      max_step_y: 1.0
      max_step_xy: 1.0
      max_step_z: 1.0
      max_step_angular: 1.0

      x_speed_multiplier: 1.35
      y_speed_multiplier: 1.66
      yaw_speed_multiplier: 1.66

      stability_stop:
        imu:
          active: False
          pitch:
            threshold: 0.19
            vel_threshold: 1.3
          roll:
            threshold: 0.4
            vel_threshold: 5.7
        pause_duration: 3.0

      imu_y_acc_tau: 0.1

      phase_reset:
        min_phase: 0.25
        foot_pressure:
          active: False
          ground_min_pressure: 1.5
        effort:
          active: False
          joint_min_effort: 35.0
        imu:
          active: False
          y_acceleration_threshold: 2.0

      trunk_pid:
        pitch:
          p: 0.0
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: False
        roll:
          p: 0.0
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: False
