#request
Header header

# telling that this is a new animation
bool first_frame
# after this the animation is finished
bool last_frame

# this animation is comming from the motion itself, it knows what to do
# will only be checked if first_frame or last_frame is true
bool motion

# motor positions
sensor_msgs/JointState state

---
#response

bool success