##################
# IFA 2026 Field #
##################

# Settings for the standard platform league field

parameter_blackboard:
  ros__parameters:
    field:
      size:
        x: 7.45
        y: 5.01
        padding: 0.8   # Padding (area outside of the lines) of the field in all directions
      markings:
        center_circle:
          diameter: 1.3
        penalty_area:
          size:
            x: 1.65   # The distance from the goal line to the boundary of the penalty area
      goal:
        width: 1.87   # The width of the goal (center of one goal post to the other goal post)
        depth: 0.75   # The depth of the goal (distance from the goal line to the back of the goal)
