# Goal definition

# Name of the animation
string animation

# If the animation call comes from the hardware control manager,
# it should be played directly, interrupting other animations and walking
# It's probably falling or standing up
bool hcm

# Debugging controls
bool bounds # If true, only a specific range of keyframes will be played
# Keyframe where we want to start (if not specified, the animation will start from the beginning)
uint8 start
# Keyframe where we want to end
uint8 end



---
# Result definition
bool successful

---
# Feedback
uint8 percent_done
