# -*- coding:utf-8 -*-
"""
Visualization Keys
^^^^^^^^^^^^^^^^^^

Contains all keys for visualization

History:
''''''''

* 26.04.15: Created (Marc Bestmann)
"""

VIZ_KEY_VIZ_ACTIVE = "VIZ_KEY_VIZ_ACTIVE"
""" Is visualization active """

VIZ_KEY_BALL_RATING_OUT = "VIZ_KEY_BALL_RATING_OUT"
""" by rating sorted out balls (x, y, r)"""

VIZ_KEY_BALL_BODY_OUT = "VIZ_KEY_BALL_BODY_OUT"

VIZ_KEY_BALL_SMALL_OUT = "VIZ_KEY_BALL_SMALL_OUT"

VIZ_KEY_BALL_HUGE_OUT = "VIZ_KEY_BALL_HUGE_OUT"

VIZ_KEY_BALL_FAR_OUT = "VIZ_KEY_BALL_FAR_OUT"

VIZ_KEY_BALL_POSSIBLE_LIST = "VIZ_KEY_BALL_POSSIBLE_LIST"

VIZ_KEY_BEST_BALL_NUMBER = "VIZ_KEY_BEST_BALL_NUMBER"

VIZ_KEY_CANDIDATE_SHAPES = "VIZ_KEY_CANDIDATE_SHAPES"

VIZ_KEY_ORANGE_BALL_SHAPE = "VIZ_KEY_ORANGE_BALL_SHAPE"

VIZ_KEY_RATED_OUT_SHAPES = "VIZ_KEY_RATED_OUT_SHAPES"

VIZ_KEY_BODY_OUT_SHAPES = "VIZ_KEY_BODY_OUT_SHAPES"

VIZ_KEY_SMALL_OUT_SHAPES = "VIZ_KEY_SMALL_OUT_SHAPES"

VIZ_KEY_HUGE_OUT_SHAPES = "VIZ_KEY_HUGE_OUT_SHAPES"

VIZ_KEY_FAR_OUT_SHAPES = "VIZ_KEY_FAR_OUT_SHAPES"

VIZ_KEY_BALL_STATISTIC = "VIZ_KEY_BALL_STATISTIC"

VIZ_KEY_BALL_POSSIBLE_LIST_SHAPE = "VIZ_KEY_BALL_POSSIBLE_LIST_SHAPE"

VIZ_KEY_BALL_LEGEND = "VIZ_KEY_BALL_LEGEND"

VIZ_KEY_NUMBER_IMAGES = "VIZ_KEY_NUMBER_IMAGES"

VIZ_KEY_INDEX_IMAGE = "VIZ_KEY_INDEX_IMAGE"

VIZ_KEY_REQUEST_NEW_FRAME = "VIZ_KEY_REQUEST_NEW_FRAME"

VIZ_KEY_CURRENT_FRAME = "VIZ_KEY_CURRENT_FRAME"

VIZ_KEY_SORTED_OUT_GOALS = "VIZ_KEY_SORTED_OUT_GOALS"

VIZ_KEY_GOAL_FINAL_SHAPE = "VIZ_KEY_GOAL_FINAL"

VIZ_KEY_GOAL_CANDIDATE_SHAPES = "VIZ_KEY_GOAL_CANDIDATE_SHAPES"

VIZ_KEY_GOAL_SORTED_OUT_SHAPES = "VIZ_KEY_GOAL_SORTED_OUT_SHAPES"

VIZ_KEY_ACTIVE_FEATURES = "VIZ_KEY_ACTIVE_FEATURES"
