# Save the current area memory to a file

# Path of an area localization file that describes the surroundings. Use ".area" extension.
string area_file_path
---
bool success   # indicate successful run of service
string message # informational, e.g. for error messages
