##########
# Webots #
##########

# Settings override for the webots simulator field

bitbots_localization:
  ros__parameters:
    field:
      size:
        x: 9.0
        y: 6.0
      padding: 1.0
      initialization:
        single_pose:
          x: -2.0
          y: 0.0
          t: 0.0
