walking:
  ros__parameters:
    engine:
      double_support_ratio: 0.344712138054358
      first_step_swing_factor: 0.655732438779827
      foot_distance: 0.179014406520205
      foot_rise: 0.0691599578967284
      freq: 1.54162204748046
      trunk_height: 0.323123253829563
      trunk_phase: -0.0743933506894948
      trunk_pitch: 0.21401534769464
      trunk_pitch_p_coef_forward: 0.278779805055009
      trunk_pitch_p_coef_turn: 2.3824552096713
      trunk_swing: 0.359304758903818
      trunk_x_offset: -0.0495856564961475
      trunk_y_offset: 0.00109375178761593
      trunk_z_movement: 0.0731081454325577
      directions_left: 49.0
      fall_sum: 0.0
      first_step_trunk_phase: -0.5
      foot_apex_phase: 0.5
      foot_overshoot_phase: 1.0
      foot_overshoot_ratio: 0.0
      foot_put_down_phase: 1.0
      foot_z_pause: 0.0
      gyro_obj: 0.006583455791882188
      last_pose_obj: 0.2759057237031307
      orientation_obj: 0.1545917664648956
      pose_obj: 0.11224960109409649
      stability_obj: 0.0805876111283889
      termination_reason: pose
      trunk_pause: 0.0
      s_nsga2:generation: 10.0
      s_nsga2:parents: [215322, 215250]

    node:
      # update frequency of the engine
      engine_freq: 1000.0

      # parameters for bioIK
      ik:
        timeout: 0.001
        reset: True

      debug_active: False

      max_step_x: 1000.0
      max_step_y: 1000.0
      max_step_xy: 1000.0
      max_step_z: 1000.0
      max_step_angular: 1000.0

      x_speed_multiplier: 1.0
      y_speed_multiplier: 1.0
      yaw_speed_multiplier: 1.0

      stability_stop:
        imu:
          active: False
          pitch:
            threshold: 0.19
            vel_threshold: 1.3
          roll:
            threshold: 0.4
            vel_threshold: 5.7
        pause_duration: 3.0

      imu_y_acc_tau: 0.1

      phase_reset:
        min_phase: 0.25
        foot_pressure:
          active: False
          ground_min_pressure: 1.5
        effort:
          active: False
          joint_min_effort: 35
        imu:
          active: False
          y_acceleration_threshold: 2.0

      trunk_pid:
        pitch:
          p: 0.0
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: False
        roll:
          p: 0.0
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: False
