walking:
  ros__parameters:
    engine:
      # Full walk cycle frequency
      # (in Hz, > 0)
      freq: 1.3
      # Length of double support phase in half cycle
      # (ratio, [0:1])
      double_support_ratio: 0.05
      # Lateral distance between the feet center
      # (in m, >= 0)
      foot_distance: 0.2
      # Maximum flying foot height
      # (in m, >= 0)
      foot_rise: 0.06
      # Pause of Z movement on highest point
      # (single support cycle ratio, [0,1])
      foot_z_pause: 0.0
      # Phase of flying foot apex
      # (single support cycle phase, [0:1])
      foot_apex_phase: 0.5
      # Let the foot's downward trajectory end above the ground
      # this is helpful if the support leg bends
      # (in m, >= 0)
      foot_put_down_z_offset: 0.0
      #Phase time for moving the foot from Z offset to ground
      #(in half cycle ratio [0:1])
      foot_put_down_phase: 1.0
      # Foot X/Y overshoot in ratio of step length
      # (ratio, >= 0)
      foot_overshoot_ratio: 0.1
      # Foot X/Y overshoot phase
      # (single support cycle phase, [foot_apex_phase:1]
      foot_overshoot_phase: 0.85
      # Height of the trunk from ground
      # (in m, > 0)
      trunk_height: 0.40
      # Trunk pitch orientation
      # (in rad)
      trunk_pitch: 0.14
      # Phase offset of trunk oscillation
      # (half cycle phase, [-1:1])
      trunk_phase: -0.1
      # Trunk forward offset
      # (in m)
      trunk_x_offset: 0.0
      # Trunk lateral offset
      # (in m)
      trunk_y_offset: 0.005
      # Trunk lateral oscillation amplitude ratio
      # (ratio, >= 0)
      trunk_swing: 0.2
      # Trunk swing pause length in phase at apex
      # (half cycle ratio, [0:1])
      trunk_pause: 0.0
      # Trunk forward offset proportional to forward step
      # (in m)
      trunk_x_offset_p_coef_forward: 0.0
      # Trunk forward offset proportional to rotation step
      # (in m/rad)
      trunk_x_offset_p_coef_turn: 0.0
      # Trunk pitch orientation proportional to forward step
      # (in rad/m)
      trunk_pitch_p_coef_forward: 1.2
      # Trunk pitch orientation proportional to rotation step
      # (in 1)
      trunk_pitch_p_coef_turn: -0.05

      kick_length: 0.12
      kick_vel: 0.2
      kick_phase: 0.28
      kick_put_down_phase: 0.8
      kick_rise_factor: 1.5

      first_step_swing_factor: 1.0
      first_step_trunk_phase: -0.5

      trunk_z_movement: 0.0

    node:
      # update frequency of the engine
      engine_freq: 500.0

      # parameters for bioIK
      ik:
        timeout: 0.01
        reset: True

      debug_active: True

      max_step_x: 10000.0
      max_step_y: 10000.0
      max_step_xy: 10000.0
      max_step_z: 100000.0
      max_step_angular: 10000.0

      x_speed_multiplier: 1.0
      y_speed_multiplier: 1.0
      yaw_speed_multiplier: 1.0

      stability_stop:
        imu:
          active: False
          pitch:
            threshold: 0.19
            vel_threshold: 1.3
          roll:
            threshold: 0.4
            vel_threshold: 5.7
        pause_duration: 3.0

      imu_y_acc_tau: 0.1

      phase_reset:
        min_phase: 0.25
        foot_pressure:
          active: True
          ground_min_pressure: 1.5
        effort:
          active: False
          joint_min_effort: 35
        imu:
          active: False
          y_acceleration_threshold: 2.0

      trunk_pid:
        pitch:
          p: 0.25
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: False
        roll:
          p: 0.111
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: False
