/**:
  ros__parameters:
    use_sim_time: true
walking:
  ros__parameters:
    engine:
      double_support_ratio: 0.3024282674039902
      foot_distance: 0.08001096328465564
      foot_rise: 0.05998189641726781
      freq: 2.845618820911015
      trunk_height: 0.2983030559136974
      trunk_phase: 0.12827615590083075
      trunk_pitch: -0.055110618389264815
      trunk_pitch_p_coef_forward: -0.12637788250249904
      trunk_pitch_p_coef_turn: -0.2667355426805498
      trunk_swing: 0.01645550463939423
      trunk_x_offset: 0.006597025399470368
      trunk_y_offset: 0.000866895485109485
      trunk_z_movement: 0.023616176690388607
      first_step_swing_factor: 1.0
      first_step_trunk_phase: -0.5
      foot_apex_phase: 0.5
      foot_overshoot_phase: 1.0
      foot_overshoot_ratio: 0.0
      foot_put_down_phase: 1.0
      foot_put_down_z_offset: 0.0
      foot_z_pause: 0.0
      trunk_pause: 0.0
      trunk_x_offset_p_coef_forward: 0.0
      trunk_x_offset_p_coef_turn: 0.0

      kick_length: 0.09
      kick_vel: 0.2
      kick_phase: 0.75

    node:
      # update frequency of the engine
      engine_freq: 125.0

      # parameters for bioIK
      ik:
        timeout: 0.01
        reset: False

      debug_active: True

      max_step_x: 1000.0
      max_step_y: 1000.0
      max_step_xy: 1000.0
      max_step_z: 1000.0
      max_step_angular: 1000.0

      stability_stop:
        imu:
          active: False
          pitch:
            threshold: 0.19
            vel_threshold: 1.3
          roll:
            threshold: 0.4
            vel_threshold: 5.7
        pause_duration: 3.0

      imu_y_acc_tau: 0.1

      phase_reset:
        min_phase: 0.25
        foot_pressure:
          active: False
          ground_min_pressure: 1.5
        effort:
          active: False
          joint_min_effort: 3.0
        imu:
          active: False
          y_acceleration_threshold: 2.0

      x_speed_multiplier: 1.0
      y_speed_multiplier: 1.0
      yaw_speed_multiplier: 1.0

      trunk_pid:
        pitch:
          p: 0.0
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: False
        roll:
          p: 0.0
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: False
